### ISSUE TITLE
Question: Is this compatible only with FrSky Taranis radio or can support other radios?

### ISSUE THREAD

**Issue by palaniraja** [alexeystn/lua-fpv-sim#2]
Not an issue but a query.

New to RC hobby, was searching for inradio sim for my radiomaster-tx16s and found this page. Wondering if this is only applicable for FrSky Taransis as you mentioned in the `README` or can support any radio?

if this is only for selected model, how can I port this to radiomaster-tx16s, any pointer would be helpful. 

p.s: thank you for sharing the script

**Comment by alexeystn** [comment]
Good news: any radio is supported now.
I made a few changes to be able to run this script on TX16S and other radios with large LCDs.

**Comment by palaniraja** [comment]
Thank you!
